### ISSUE TITLE
if i do command Ctrl+Down n times, then Ctrl+Up m times, i get this look of caret

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#10]
![Screenshot_2022-07-01_20-50-37](https://user-images.githubusercontent.com/4154978/176945896-9298473d-268b-4b7f-bc73-94acb20f094d.png)

**Comment by Alexey-T** [comment]
maybe it helps?

ed.set_prop(PROP_LAST_LINE_ON_TOP, ..)

**Comment by veksha** [comment]
ctrl+Up/Down is native feature of Editor/Memo? it scrolls screen and keeps caret in the view?
I can implement custom scrolling or maybe it's better to just call `self.screen.refresh_caret()` on ctrl+Up/Down keys.

**Comment by Alexey-T** [comment]
>ctrl+Up/Down is native feature of Editor/Memo?

yes

> it scrolls memo and keeps caret in the view?

not sure it always keeps.
![Screenshot from 2022-07-01 21-25-34](https://user-images.githubusercontent.com/4154978/176950020-5aee387f-f17f-4173-91a9-e96208f1a2df.png)

**Comment by Alexey-T** [comment]
>I can implement custom scrolling or maybe it's better to just call 

maybe use ed.set_prop(PROP_LAST_LINE_ON_TOP, ..)

**Comment by veksha** [comment]
> maybe use ed.set_prop(PROP_LAST_LINE_ON_TOP, ..)

I can enable it. But it will do nothing to caret, it will just insert empty space at the bottom.
`self.memo.set_prop(PROP_LAST_LINE_ON_TOP, True)`

**Comment by Alexey-T** [comment]
it must be False! so use won't scroll the text after empty space

**Comment by veksha** [comment]
it is already False (it is not configured at all, i mean).
empty lines that are trailing below the text is a minor problem.

caret can also be ABOVE the correct place (if you press ctrl-up).
but caret placement is something not that important. there is a screen.cursor variable that tracks of real cursor position.
as soon as you start typing text it will snap to correct location.
not big deal, i think.

**Comment by Alexey-T** [comment]
Ok

**Comment by veksha** [comment]
didn't know that it obeys global option `PROP_LAST_LINE_ON_TOP` if not explicitly set in the code.
you probably have it enabled globally. I have it disabled in Options Editor Lite.
