### ISSUE TITLE
current dir in terminal

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#12]
- pwd prints /home/user
- now I open a project, open some file from it. pwd still prints the same. but I want that pwd prints folder of opened file
- now I open some random file. pwd still prints the same.

![Screenshot from 2022-07-02 09-00-09](https://user-images.githubusercontent.com/4154978/176988717-2a5f22ec-e01d-48dc-b2b4-e7aa07bd84ca.png)

**Comment by Alexey-T** [comment]
Terminal+ supports changing of current dir to the

- folder of current file
- folder of MainFile of cur proj
- 1st folder in proj

by option

**Comment by veksha** [comment]
I can't find this functionality in Terminal+.
I see that I can configure start_dir only.
and when user have created tabs for all documents, you can run "Toggle focus" command from Command palette and it will go to the tab that is "connected" to current file opened in Cud.
I see no automatic changing of dir in running terminal.

we can't just change directory in running terminal, for obvious reasons.

And i don't think that implementing tabs like in Terminal+ is nice way to go, when we already can have icons in bottom panel (or maybe it's called bottom side of the side panel)
![image](https://user-images.githubusercontent.com/275333/177005741-4d392e4e-96ac-41fc-b7c1-1429ec7fb914.png)

to create new tab we can run command from Command palette, or if supported by API implement right-click menu on these icons.
I don't think current API supports right-click context menus of these icons on screenshot.

**Comment by Alexey-T** [comment]
>I don't think current API supports right-click context menus 

API dont support this yet

Ok, you are right, but 

- i opened ExTerminal
- i opened some file in editor
- now i want to do some work in ExTerminal but its 'pwd' is different dir - how to change it to dir of current file?

**Comment by veksha** [comment]
> ExTerminal

nice name 👍 

> now i want to do some work in ExTerminal but its 'pwd' is different dir - how to change it to dir of current file?

all you can do is just restart Cud. Because only one instance is supported for now.
In Terminal+ it is not automatic process too. You still must press "+" button to spawn new terminal in new tab.

**Comment by veksha** [comment]
when issue #8 will be resolved you will have second option to just type exit. and terminal will respawn with new pwd.
