### ISSUE TITLE
 'cuda_example_terminal.ini'

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#14]
if we have only 3 opts (or even 6) it's better to REuse settings/plugins.ini,
section 'ex_terminal'.

**Comment by veksha** [comment]
okay. i see that it is global settings ini file, but what do you mean by "REuse"?

**Comment by Alexey-T** [comment]
reuse - coz the plugins.ini is for all plugins, used by many,

**Comment by veksha** [comment]
done

**Comment by Alexey-T** [comment]
[cuda_exterminal]
->
[exterminal]
please

**Comment by veksha** [comment]
oh yes. done.
