### ISSUE TITLE
cannot find Bash path

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#4]
Ubuntu 20
```
[Errno 2] No such file or directory: ''
/bin/bash
```
 main PC: I already have bash as /bin/bash so why the error??

**Comment by Alexey-T** [comment]
maybe becase Term command not found here?

TERM = "xterm-256color"

I only have 'xterm' and 'gnome-terminal' on main PC

**Comment by Alexey-T** [comment]
![ba](https://user-images.githubusercontent.com/4154978/176860946-794190a7-cfb9-4721-9a9e-40d1beb3bc1f.png)

**Comment by veksha** [comment]
this happened to me too when I install plugin for the first time and don't reload Cud. Weird bug.
After restarting once this bug will go away. I will investigate it later.
Thanks for the report!

**Comment by Alexey-T** [comment]
I did reload the Cud. and I updated the plug now. still the same..

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/176891575-bd189c43-3367-4488-81a3-7a8f0ba544c1.png)

works ok on Ubuntu 20.04.4 for me. tested also on Lubuntu.

**Comment by veksha** [comment]
try to change slashes to double-slashes in the code (2nd line).
SHELL_UNIX = '//bin//bash'

for me it makes no difference, but maybe it will work for you.

(or SHELL_UNIX = r'/bin/bash')

**Comment by veksha** [comment]
i found a reason. it's wrong/empty `cwd` current working directory.. will fix it soon!

**Comment by veksha** [comment]
fixed. please try.

**Comment by Alexey-T** [comment]
hey-- it works good!

Great. But can you write in the readme file (for all) the advantages over Terminal+ ?

![Screenshot from 2022-07-01 15-28-00](https://user-images.githubusercontent.com/4154978/176894443-aaa580a4-6717-4720-bb1e-7c2264493227.png)

**Comment by veksha** [comment]
> hey-- it works good!

nice :)

> Great. But can you write in the readme file (for all) the advantages over Terminal+ ?

of course.

**Comment by veksha** [comment]
added simple readme file
