### ISSUE TITLE
Esc key

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#7]
consider to make Esc going to editor (focus editor). at least by option 'esc_focuses_editor=1'.

import cudatext_cmd as cmds
...
ed.cmd(cmds.cmd_FocusEditor)

**Comment by veksha** [comment]
added `esc_focuses_editor` setting as suggested.

**Comment by veksha** [comment]
wait what? I forgot to import cmds, but it still focuses editor. despite the errors in the Console log.

**Comment by veksha** [comment]
I was triggering wrong editor. fixed now.
