### ISSUE TITLE
word-deletion cmds

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_example_terminal#9]
if it's not hard, pls support these 2 hotkeys

![Screenshot_2022-07-01_20-03-20](https://user-images.githubusercontent.com/4154978/176939065-719b9ab1-b484-4c50-a780-14eccb972095.png)

**Comment by veksha** [comment]
(before reading this grab latest changes first!)

bash uses `readline` lib. you can configure it for your liking.

`man readline`:
```
kill-word (M-d)
backward-kill-word (M-Rubout)
```
In human language its:
M-d - Alt+D
M-Rubout - Alt+BkSp

you can bind backward-kill-word to Ctrl+BkSp using the following command in `~/.bashrc`
```
bind '"\C-h":backward-kill-word'
...
```
for example.

or to configure `readline` globally edit `~/.inputrc` file:
```
# Ctrl-Delete: delete next word
"\e[3;5~": shell-kill-word

# Ctrl-Backspace
"\C-H": shell-backward-kill-word
```

please, try it.
On Windows cmd.exe already supports these combinations.
